### PR TITLE
Add benchmark for `expo-sqlite/next`

### PR DESCRIPTION
**Pull request by XantreDev**
300k query
image
image

200 rows query
image

<details>
  <summary>Raw data</summary>
  
  
image
image
image
image

  
</details>

### CODE REVIEW

**Comment by ospfranco** [comment]
Awesome, thanks a lot!

**Comment by ospfranco** [comment]
Oscar Franco Screen 000593

I tried to run the app and got the following error

**Comment by ospfranco** [comment]
I updated to canary to get it to compile but the code doesn't look correct. Also, you don't want to measure transactions.

Oscar Franco Screen 000594

Going to revert it for now

**Comment by XantreDev** [comment]
image
image

**Comment by XantreDev** [comment]
I've tested it with expo go

**Comment by ospfranco** [comment]
It's alright, I will try it on my own, the code looks very abstract and I won't maintain it. This is a throw-away project. Thanks for the info though!

**Pull request merged**
